// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Test Assignment Backend Service
//
//	Test Assignment WebSite Backend Service
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: development
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
