// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Test Assignment WebSite Backend Service",
    "title": "Test Assignment Backend Service",
    "version": "development"
  },
  "paths": {
    "/song": {
      "post": {
        "tags": [
          "Song"
        ],
        "summary": "Add Song",
        "operationId": "CreateSong",
        "parameters": [
          {
            "description": "Create song Body",
            "name": "CreateSong",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateSongBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Register Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CreateSongBody": {
      "type": "object",
      "required": [
        "group",
        "song"
      ],
      "properties": {
        "group": {
          "type": "string"
        },
        "song": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Test Assignment WebSite Backend Service",
    "title": "Test Assignment Backend Service",
    "version": "development"
  },
  "paths": {
    "/song": {
      "post": {
        "tags": [
          "Song"
        ],
        "summary": "Add Song",
        "operationId": "CreateSong",
        "parameters": [
          {
            "description": "Create song Body",
            "name": "CreateSong",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateSongBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Register Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CreateSongBody": {
      "type": "object",
      "required": [
        "group",
        "song"
      ],
      "properties": {
        "group": {
          "type": "string"
        },
        "song": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
