// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Test Assignment WebSite Backend Service",
    "title": "Test Assignment Backend Service",
    "version": "development"
  },
  "paths": {
    "/song": {
      "post": {
        "tags": [
          "Song"
        ],
        "summary": "Create Song",
        "operationId": "CreateSong",
        "parameters": [
          {
            "description": "Create Song Body",
            "name": "CreateSong",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateSongBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Create Song Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/song/{id}": {
      "delete": {
        "tags": [
          "Song"
        ],
        "summary": "Delete Song",
        "operationId": "DeleteSong",
        "parameters": [
          {
            "type": "integer",
            "description": "ID of song",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Delete Song Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "tags": [
          "Song"
        ],
        "summary": "Update Song",
        "operationId": "UpdateSong",
        "parameters": [
          {
            "type": "integer",
            "description": "ID of song",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Create Song Body",
            "name": "UpdateSong",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateSongBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Update Song Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/song/{id}/verse": {
      "get": {
        "tags": [
          "Song"
        ],
        "summary": "Get Song Verse",
        "operationId": "GetSongVerse",
        "parameters": [
          {
            "type": "integer",
            "description": "Offset Configs",
            "name": "offset",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "description": "Offset Configs",
            "name": "limit",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "description": "ID of song",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get Song Verse Response",
            "schema": {
              "$ref": "#/definitions/SongVersesResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/songs": {
      "get": {
        "tags": [
          "Songs"
        ],
        "summary": "Get Songs",
        "operationId": "GetSongs",
        "parameters": [
          {
            "type": "integer",
            "description": "Offset Configs",
            "name": "offset",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "description": "Offset Configs",
            "name": "limit",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "Filter Song By Name",
            "name": "FilterSongByName",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter Song By Group",
            "name": "FilterSongByGroup",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter Song By Text",
            "name": "FilterSongByText",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter Song By Release Date",
            "name": "FilterSongByReleaseDate",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter Song By Link",
            "name": "FilterSongByLink",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get Songs Response",
            "schema": {
              "$ref": "#/definitions/Songs"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CreateSongBody": {
      "type": "object",
      "required": [
        "group",
        "song"
      ],
      "properties": {
        "group": {
          "type": "string"
        },
        "song": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Song": {
      "type": "object",
      "required": [
        "release_date",
        "text",
        "link"
      ],
      "properties": {
        "group": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "link": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "release_date": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "SongVerse": {
      "type": "object",
      "required": [
        "verse"
      ],
      "properties": {
        "verse": {
          "type": "string"
        }
      }
    },
    "SongVersesResponse": {
      "type": "object",
      "required": [
        "verses"
      ],
      "properties": {
        "verses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SongVerse"
          }
        }
      }
    },
    "Songs": {
      "type": "object",
      "required": [
        "count"
      ],
      "properties": {
        "count": {
          "type": "integer"
        },
        "songs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Song"
          }
        }
      }
    },
    "UpdateSongBody": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        },
        "link": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "release_date": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Test Assignment WebSite Backend Service",
    "title": "Test Assignment Backend Service",
    "version": "development"
  },
  "paths": {
    "/song": {
      "post": {
        "tags": [
          "Song"
        ],
        "summary": "Create Song",
        "operationId": "CreateSong",
        "parameters": [
          {
            "description": "Create Song Body",
            "name": "CreateSong",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateSongBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Create Song Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/song/{id}": {
      "delete": {
        "tags": [
          "Song"
        ],
        "summary": "Delete Song",
        "operationId": "DeleteSong",
        "parameters": [
          {
            "type": "integer",
            "description": "ID of song",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Delete Song Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "tags": [
          "Song"
        ],
        "summary": "Update Song",
        "operationId": "UpdateSong",
        "parameters": [
          {
            "type": "integer",
            "description": "ID of song",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Create Song Body",
            "name": "UpdateSong",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateSongBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Update Song Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/song/{id}/verse": {
      "get": {
        "tags": [
          "Song"
        ],
        "summary": "Get Song Verse",
        "operationId": "GetSongVerse",
        "parameters": [
          {
            "minimum": 0,
            "type": "integer",
            "description": "Offset Configs",
            "name": "offset",
            "in": "query",
            "required": true
          },
          {
            "minimum": 0,
            "type": "integer",
            "description": "Offset Configs",
            "name": "limit",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "description": "ID of song",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get Song Verse Response",
            "schema": {
              "$ref": "#/definitions/SongVersesResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/songs": {
      "get": {
        "tags": [
          "Songs"
        ],
        "summary": "Get Songs",
        "operationId": "GetSongs",
        "parameters": [
          {
            "minimum": 0,
            "type": "integer",
            "description": "Offset Configs",
            "name": "offset",
            "in": "query",
            "required": true
          },
          {
            "minimum": 0,
            "type": "integer",
            "description": "Offset Configs",
            "name": "limit",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "Filter Song By Name",
            "name": "FilterSongByName",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter Song By Group",
            "name": "FilterSongByGroup",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter Song By Text",
            "name": "FilterSongByText",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter Song By Release Date",
            "name": "FilterSongByReleaseDate",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter Song By Link",
            "name": "FilterSongByLink",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get Songs Response",
            "schema": {
              "$ref": "#/definitions/Songs"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CreateSongBody": {
      "type": "object",
      "required": [
        "group",
        "song"
      ],
      "properties": {
        "group": {
          "type": "string"
        },
        "song": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Song": {
      "type": "object",
      "required": [
        "release_date",
        "text",
        "link"
      ],
      "properties": {
        "group": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "link": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "release_date": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "SongVerse": {
      "type": "object",
      "required": [
        "verse"
      ],
      "properties": {
        "verse": {
          "type": "string"
        }
      }
    },
    "SongVersesResponse": {
      "type": "object",
      "required": [
        "verses"
      ],
      "properties": {
        "verses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SongVerse"
          }
        }
      }
    },
    "Songs": {
      "type": "object",
      "required": [
        "count"
      ],
      "properties": {
        "count": {
          "type": "integer"
        },
        "songs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Song"
          }
        }
      }
    },
    "UpdateSongBody": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        },
        "link": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "release_date": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    }
  }
}`))
}
