// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteSongParams creates a new DeleteSongParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteSongParams() *DeleteSongParams {
	return &DeleteSongParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSongParamsWithTimeout creates a new DeleteSongParams object
// with the ability to set a timeout on a request.
func NewDeleteSongParamsWithTimeout(timeout time.Duration) *DeleteSongParams {
	return &DeleteSongParams{
		timeout: timeout,
	}
}

// NewDeleteSongParamsWithContext creates a new DeleteSongParams object
// with the ability to set a context for a request.
func NewDeleteSongParamsWithContext(ctx context.Context) *DeleteSongParams {
	return &DeleteSongParams{
		Context: ctx,
	}
}

// NewDeleteSongParamsWithHTTPClient creates a new DeleteSongParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteSongParamsWithHTTPClient(client *http.Client) *DeleteSongParams {
	return &DeleteSongParams{
		HTTPClient: client,
	}
}

/*
DeleteSongParams contains all the parameters to send to the API endpoint

	for the delete song operation.

	Typically these are written to a http.Request.
*/
type DeleteSongParams struct {

	/* ID.

	   ID of song
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete song params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSongParams) WithDefaults() *DeleteSongParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete song params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSongParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete song params
func (o *DeleteSongParams) WithTimeout(timeout time.Duration) *DeleteSongParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete song params
func (o *DeleteSongParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete song params
func (o *DeleteSongParams) WithContext(ctx context.Context) *DeleteSongParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete song params
func (o *DeleteSongParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete song params
func (o *DeleteSongParams) WithHTTPClient(client *http.Client) *DeleteSongParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete song params
func (o *DeleteSongParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete song params
func (o *DeleteSongParams) WithID(id int64) *DeleteSongParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete song params
func (o *DeleteSongParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSongParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
