// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSongVerseParams creates a new GetSongVerseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSongVerseParams() *GetSongVerseParams {
	return &GetSongVerseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSongVerseParamsWithTimeout creates a new GetSongVerseParams object
// with the ability to set a timeout on a request.
func NewGetSongVerseParamsWithTimeout(timeout time.Duration) *GetSongVerseParams {
	return &GetSongVerseParams{
		timeout: timeout,
	}
}

// NewGetSongVerseParamsWithContext creates a new GetSongVerseParams object
// with the ability to set a context for a request.
func NewGetSongVerseParamsWithContext(ctx context.Context) *GetSongVerseParams {
	return &GetSongVerseParams{
		Context: ctx,
	}
}

// NewGetSongVerseParamsWithHTTPClient creates a new GetSongVerseParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSongVerseParamsWithHTTPClient(client *http.Client) *GetSongVerseParams {
	return &GetSongVerseParams{
		HTTPClient: client,
	}
}

/*
GetSongVerseParams contains all the parameters to send to the API endpoint

	for the get song verse operation.

	Typically these are written to a http.Request.
*/
type GetSongVerseParams struct {

	/* ID.

	   ID of song
	*/
	ID int64

	/* Limit.

	   Offset Configs
	*/
	Limit int64

	/* Offset.

	   Offset Configs
	*/
	Offset int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get song verse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSongVerseParams) WithDefaults() *GetSongVerseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get song verse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSongVerseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get song verse params
func (o *GetSongVerseParams) WithTimeout(timeout time.Duration) *GetSongVerseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get song verse params
func (o *GetSongVerseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get song verse params
func (o *GetSongVerseParams) WithContext(ctx context.Context) *GetSongVerseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get song verse params
func (o *GetSongVerseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get song verse params
func (o *GetSongVerseParams) WithHTTPClient(client *http.Client) *GetSongVerseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get song verse params
func (o *GetSongVerseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get song verse params
func (o *GetSongVerseParams) WithID(id int64) *GetSongVerseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get song verse params
func (o *GetSongVerseParams) SetID(id int64) {
	o.ID = id
}

// WithLimit adds the limit to the get song verse params
func (o *GetSongVerseParams) WithLimit(limit int64) *GetSongVerseParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get song verse params
func (o *GetSongVerseParams) SetLimit(limit int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get song verse params
func (o *GetSongVerseParams) WithOffset(offset int64) *GetSongVerseParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get song verse params
func (o *GetSongVerseParams) SetOffset(offset int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetSongVerseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// query param limit
	qrLimit := o.Limit
	qLimit := swag.FormatInt64(qrLimit)
	if qLimit != "" {

		if err := r.SetQueryParam("limit", qLimit); err != nil {
			return err
		}
	}

	// query param offset
	qrOffset := o.Offset
	qOffset := swag.FormatInt64(qrOffset)
	if qOffset != "" {

		if err := r.SetQueryParam("offset", qOffset); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
