// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/TestAssignment/internal/api/definition"
)

// GetSongsReader is a Reader for the GetSongs structure.
type GetSongsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSongsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSongsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSongsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSongsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /songs] GetSongs", response, response.Code())
	}
}

// NewGetSongsOK creates a GetSongsOK with default headers values
func NewGetSongsOK() *GetSongsOK {
	return &GetSongsOK{}
}

/*
GetSongsOK describes a response with status code 200, with default header values.

Get Songs Response
*/
type GetSongsOK struct {
	Payload *models.Songs
}

// IsSuccess returns true when this get songs o k response has a 2xx status code
func (o *GetSongsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get songs o k response has a 3xx status code
func (o *GetSongsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get songs o k response has a 4xx status code
func (o *GetSongsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get songs o k response has a 5xx status code
func (o *GetSongsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get songs o k response a status code equal to that given
func (o *GetSongsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get songs o k response
func (o *GetSongsOK) Code() int {
	return 200
}

func (o *GetSongsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /songs][%d] getSongsOK %s", 200, payload)
}

func (o *GetSongsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /songs][%d] getSongsOK %s", 200, payload)
}

func (o *GetSongsOK) GetPayload() *models.Songs {
	return o.Payload
}

func (o *GetSongsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Songs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSongsBadRequest creates a GetSongsBadRequest with default headers values
func NewGetSongsBadRequest() *GetSongsBadRequest {
	return &GetSongsBadRequest{}
}

/*
GetSongsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetSongsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get songs bad request response has a 2xx status code
func (o *GetSongsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get songs bad request response has a 3xx status code
func (o *GetSongsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get songs bad request response has a 4xx status code
func (o *GetSongsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get songs bad request response has a 5xx status code
func (o *GetSongsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get songs bad request response a status code equal to that given
func (o *GetSongsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get songs bad request response
func (o *GetSongsBadRequest) Code() int {
	return 400
}

func (o *GetSongsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /songs][%d] getSongsBadRequest %s", 400, payload)
}

func (o *GetSongsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /songs][%d] getSongsBadRequest %s", 400, payload)
}

func (o *GetSongsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetSongsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSongsInternalServerError creates a GetSongsInternalServerError with default headers values
func NewGetSongsInternalServerError() *GetSongsInternalServerError {
	return &GetSongsInternalServerError{}
}

/*
GetSongsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetSongsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get songs internal server error response has a 2xx status code
func (o *GetSongsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get songs internal server error response has a 3xx status code
func (o *GetSongsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get songs internal server error response has a 4xx status code
func (o *GetSongsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get songs internal server error response has a 5xx status code
func (o *GetSongsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get songs internal server error response a status code equal to that given
func (o *GetSongsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get songs internal server error response
func (o *GetSongsInternalServerError) Code() int {
	return 500
}

func (o *GetSongsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /songs][%d] getSongsInternalServerError %s", 500, payload)
}

func (o *GetSongsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /songs][%d] getSongsInternalServerError %s", 500, payload)
}

func (o *GetSongsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetSongsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
