// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	models "github.com/Maksim646/TestAssignment/internal/api/definition"
)

// NewUpdateSongParams creates a new UpdateSongParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateSongParams() *UpdateSongParams {
	return &UpdateSongParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSongParamsWithTimeout creates a new UpdateSongParams object
// with the ability to set a timeout on a request.
func NewUpdateSongParamsWithTimeout(timeout time.Duration) *UpdateSongParams {
	return &UpdateSongParams{
		timeout: timeout,
	}
}

// NewUpdateSongParamsWithContext creates a new UpdateSongParams object
// with the ability to set a context for a request.
func NewUpdateSongParamsWithContext(ctx context.Context) *UpdateSongParams {
	return &UpdateSongParams{
		Context: ctx,
	}
}

// NewUpdateSongParamsWithHTTPClient creates a new UpdateSongParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateSongParamsWithHTTPClient(client *http.Client) *UpdateSongParams {
	return &UpdateSongParams{
		HTTPClient: client,
	}
}

/*
UpdateSongParams contains all the parameters to send to the API endpoint

	for the update song operation.

	Typically these are written to a http.Request.
*/
type UpdateSongParams struct {

	/* UpdateSong.

	   Create Song Body
	*/
	UpdateSong *models.UpdateSongBody

	/* ID.

	   ID of song
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update song params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSongParams) WithDefaults() *UpdateSongParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update song params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSongParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update song params
func (o *UpdateSongParams) WithTimeout(timeout time.Duration) *UpdateSongParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update song params
func (o *UpdateSongParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update song params
func (o *UpdateSongParams) WithContext(ctx context.Context) *UpdateSongParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update song params
func (o *UpdateSongParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update song params
func (o *UpdateSongParams) WithHTTPClient(client *http.Client) *UpdateSongParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update song params
func (o *UpdateSongParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdateSong adds the updateSong to the update song params
func (o *UpdateSongParams) WithUpdateSong(updateSong *models.UpdateSongBody) *UpdateSongParams {
	o.SetUpdateSong(updateSong)
	return o
}

// SetUpdateSong adds the updateSong to the update song params
func (o *UpdateSongParams) SetUpdateSong(updateSong *models.UpdateSongBody) {
	o.UpdateSong = updateSong
}

// WithID adds the id to the update song params
func (o *UpdateSongParams) WithID(id int64) *UpdateSongParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update song params
func (o *UpdateSongParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSongParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.UpdateSong != nil {
		if err := r.SetBodyParam(o.UpdateSong); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
