// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateSongHandlerFunc turns a function with the right signature into a create song handler
type CreateSongHandlerFunc func(CreateSongParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateSongHandlerFunc) Handle(params CreateSongParams) middleware.Responder {
	return fn(params)
}

// CreateSongHandler interface for that can handle valid create song params
type CreateSongHandler interface {
	Handle(CreateSongParams) middleware.Responder
}

// NewCreateSong creates a new http.Handler for the create song operation
func NewCreateSong(ctx *middleware.Context, handler CreateSongHandler) *CreateSong {
	return &CreateSong{Context: ctx, Handler: handler}
}

/*
	CreateSong swagger:route POST /song Song createSong

Add Song
*/
type CreateSong struct {
	Context *middleware.Context
	Handler CreateSongHandler
}

func (o *CreateSong) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateSongParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
