// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	models "github.com/Maksim646/TestAssignment/internal/api/definition"
)

// NewCreateSongParams creates a new CreateSongParams object
//
// There are no default values defined in the spec.
func NewCreateSongParams() CreateSongParams {

	return CreateSongParams{}
}

// CreateSongParams contains all the bound params for the create song operation
// typically these are obtained from a http.Request
//
// swagger:parameters CreateSong
type CreateSongParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Create Song Body
	  Required: true
	  In: body
	*/
	CreateSong *models.CreateSongBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateSongParams() beforehand.
func (o *CreateSongParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CreateSongBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("createSong", "body", ""))
			} else {
				res = append(res, errors.NewParseError("createSong", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.CreateSong = &body
			}
		}
	} else {
		res = append(res, errors.Required("createSong", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
