// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/TestAssignment/internal/api/definition"
)

// CreateSongOKCode is the HTTP code returned for type CreateSongOK
const CreateSongOKCode int = 200

/*
CreateSongOK Create Song Response

swagger:response createSongOK
*/
type CreateSongOK struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSongOK creates CreateSongOK with default headers values
func NewCreateSongOK() *CreateSongOK {

	return &CreateSongOK{}
}

// WithPayload adds the payload to the create song o k response
func (o *CreateSongOK) WithPayload(payload *models.Error) *CreateSongOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create song o k response
func (o *CreateSongOK) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSongOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSongBadRequestCode is the HTTP code returned for type CreateSongBadRequest
const CreateSongBadRequestCode int = 400

/*
CreateSongBadRequest Bad request

swagger:response createSongBadRequest
*/
type CreateSongBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSongBadRequest creates CreateSongBadRequest with default headers values
func NewCreateSongBadRequest() *CreateSongBadRequest {

	return &CreateSongBadRequest{}
}

// WithPayload adds the payload to the create song bad request response
func (o *CreateSongBadRequest) WithPayload(payload *models.Error) *CreateSongBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create song bad request response
func (o *CreateSongBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSongBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSongInternalServerErrorCode is the HTTP code returned for type CreateSongInternalServerError
const CreateSongInternalServerErrorCode int = 500

/*
CreateSongInternalServerError Internal server error

swagger:response createSongInternalServerError
*/
type CreateSongInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSongInternalServerError creates CreateSongInternalServerError with default headers values
func NewCreateSongInternalServerError() *CreateSongInternalServerError {

	return &CreateSongInternalServerError{}
}

// WithPayload adds the payload to the create song internal server error response
func (o *CreateSongInternalServerError) WithPayload(payload *models.Error) *CreateSongInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create song internal server error response
func (o *CreateSongInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSongInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
