// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteSongHandlerFunc turns a function with the right signature into a delete song handler
type DeleteSongHandlerFunc func(DeleteSongParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSongHandlerFunc) Handle(params DeleteSongParams) middleware.Responder {
	return fn(params)
}

// DeleteSongHandler interface for that can handle valid delete song params
type DeleteSongHandler interface {
	Handle(DeleteSongParams) middleware.Responder
}

// NewDeleteSong creates a new http.Handler for the delete song operation
func NewDeleteSong(ctx *middleware.Context, handler DeleteSongHandler) *DeleteSong {
	return &DeleteSong{Context: ctx, Handler: handler}
}

/*
	DeleteSong swagger:route DELETE /song/{id} Song deleteSong

Delete Song
*/
type DeleteSong struct {
	Context *middleware.Context
	Handler DeleteSongHandler
}

func (o *DeleteSong) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteSongParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
