// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/TestAssignment/internal/api/definition"
)

// DeleteSongOKCode is the HTTP code returned for type DeleteSongOK
const DeleteSongOKCode int = 200

/*
DeleteSongOK Delete Song Response

swagger:response deleteSongOK
*/
type DeleteSongOK struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteSongOK creates DeleteSongOK with default headers values
func NewDeleteSongOK() *DeleteSongOK {

	return &DeleteSongOK{}
}

// WithPayload adds the payload to the delete song o k response
func (o *DeleteSongOK) WithPayload(payload *models.Error) *DeleteSongOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete song o k response
func (o *DeleteSongOK) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSongOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteSongBadRequestCode is the HTTP code returned for type DeleteSongBadRequest
const DeleteSongBadRequestCode int = 400

/*
DeleteSongBadRequest Bad request

swagger:response deleteSongBadRequest
*/
type DeleteSongBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteSongBadRequest creates DeleteSongBadRequest with default headers values
func NewDeleteSongBadRequest() *DeleteSongBadRequest {

	return &DeleteSongBadRequest{}
}

// WithPayload adds the payload to the delete song bad request response
func (o *DeleteSongBadRequest) WithPayload(payload *models.Error) *DeleteSongBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete song bad request response
func (o *DeleteSongBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSongBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteSongInternalServerErrorCode is the HTTP code returned for type DeleteSongInternalServerError
const DeleteSongInternalServerErrorCode int = 500

/*
DeleteSongInternalServerError Internal server error

swagger:response deleteSongInternalServerError
*/
type DeleteSongInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteSongInternalServerError creates DeleteSongInternalServerError with default headers values
func NewDeleteSongInternalServerError() *DeleteSongInternalServerError {

	return &DeleteSongInternalServerError{}
}

// WithPayload adds the payload to the delete song internal server error response
func (o *DeleteSongInternalServerError) WithPayload(payload *models.Error) *DeleteSongInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete song internal server error response
func (o *DeleteSongInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSongInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
