// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSongVerseHandlerFunc turns a function with the right signature into a get song verse handler
type GetSongVerseHandlerFunc func(GetSongVerseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSongVerseHandlerFunc) Handle(params GetSongVerseParams) middleware.Responder {
	return fn(params)
}

// GetSongVerseHandler interface for that can handle valid get song verse params
type GetSongVerseHandler interface {
	Handle(GetSongVerseParams) middleware.Responder
}

// NewGetSongVerse creates a new http.Handler for the get song verse operation
func NewGetSongVerse(ctx *middleware.Context, handler GetSongVerseHandler) *GetSongVerse {
	return &GetSongVerse{Context: ctx, Handler: handler}
}

/*
	GetSongVerse swagger:route GET /song/{id}/verse Song getSongVerse

Get Song Verse
*/
type GetSongVerse struct {
	Context *middleware.Context
	Handler GetSongVerseHandler
}

func (o *GetSongVerse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSongVerseParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
