// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/TestAssignment/internal/api/definition"
)

// GetSongVerseOKCode is the HTTP code returned for type GetSongVerseOK
const GetSongVerseOKCode int = 200

/*
GetSongVerseOK Get Song Verse Response

swagger:response getSongVerseOK
*/
type GetSongVerseOK struct {

	/*
	  In: Body
	*/
	Payload *models.SongVersesResponse `json:"body,omitempty"`
}

// NewGetSongVerseOK creates GetSongVerseOK with default headers values
func NewGetSongVerseOK() *GetSongVerseOK {

	return &GetSongVerseOK{}
}

// WithPayload adds the payload to the get song verse o k response
func (o *GetSongVerseOK) WithPayload(payload *models.SongVersesResponse) *GetSongVerseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get song verse o k response
func (o *GetSongVerseOK) SetPayload(payload *models.SongVersesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSongVerseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSongVerseBadRequestCode is the HTTP code returned for type GetSongVerseBadRequest
const GetSongVerseBadRequestCode int = 400

/*
GetSongVerseBadRequest Bad request

swagger:response getSongVerseBadRequest
*/
type GetSongVerseBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSongVerseBadRequest creates GetSongVerseBadRequest with default headers values
func NewGetSongVerseBadRequest() *GetSongVerseBadRequest {

	return &GetSongVerseBadRequest{}
}

// WithPayload adds the payload to the get song verse bad request response
func (o *GetSongVerseBadRequest) WithPayload(payload *models.Error) *GetSongVerseBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get song verse bad request response
func (o *GetSongVerseBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSongVerseBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSongVerseInternalServerErrorCode is the HTTP code returned for type GetSongVerseInternalServerError
const GetSongVerseInternalServerErrorCode int = 500

/*
GetSongVerseInternalServerError Internal server error

swagger:response getSongVerseInternalServerError
*/
type GetSongVerseInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSongVerseInternalServerError creates GetSongVerseInternalServerError with default headers values
func NewGetSongVerseInternalServerError() *GetSongVerseInternalServerError {

	return &GetSongVerseInternalServerError{}
}

// WithPayload adds the payload to the get song verse internal server error response
func (o *GetSongVerseInternalServerError) WithPayload(payload *models.Error) *GetSongVerseInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get song verse internal server error response
func (o *GetSongVerseInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSongVerseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
