// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/TestAssignment/internal/api/definition"
)

// GetSongsOKCode is the HTTP code returned for type GetSongsOK
const GetSongsOKCode int = 200

/*
GetSongsOK Get Songs Response

swagger:response getSongsOK
*/
type GetSongsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Songs `json:"body,omitempty"`
}

// NewGetSongsOK creates GetSongsOK with default headers values
func NewGetSongsOK() *GetSongsOK {

	return &GetSongsOK{}
}

// WithPayload adds the payload to the get songs o k response
func (o *GetSongsOK) WithPayload(payload *models.Songs) *GetSongsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get songs o k response
func (o *GetSongsOK) SetPayload(payload *models.Songs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSongsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSongsBadRequestCode is the HTTP code returned for type GetSongsBadRequest
const GetSongsBadRequestCode int = 400

/*
GetSongsBadRequest Bad request

swagger:response getSongsBadRequest
*/
type GetSongsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSongsBadRequest creates GetSongsBadRequest with default headers values
func NewGetSongsBadRequest() *GetSongsBadRequest {

	return &GetSongsBadRequest{}
}

// WithPayload adds the payload to the get songs bad request response
func (o *GetSongsBadRequest) WithPayload(payload *models.Error) *GetSongsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get songs bad request response
func (o *GetSongsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSongsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSongsInternalServerErrorCode is the HTTP code returned for type GetSongsInternalServerError
const GetSongsInternalServerErrorCode int = 500

/*
GetSongsInternalServerError Internal server error

swagger:response getSongsInternalServerError
*/
type GetSongsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSongsInternalServerError creates GetSongsInternalServerError with default headers values
func NewGetSongsInternalServerError() *GetSongsInternalServerError {

	return &GetSongsInternalServerError{}
}

// WithPayload adds the payload to the get songs internal server error response
func (o *GetSongsInternalServerError) WithPayload(payload *models.Error) *GetSongsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get songs internal server error response
func (o *GetSongsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSongsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
