// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/TestAssignment/internal/api/definition"
)

// UpdateSongOKCode is the HTTP code returned for type UpdateSongOK
const UpdateSongOKCode int = 200

/*
UpdateSongOK Delete Song Response

swagger:response updateSongOK
*/
type UpdateSongOK struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateSongOK creates UpdateSongOK with default headers values
func NewUpdateSongOK() *UpdateSongOK {

	return &UpdateSongOK{}
}

// WithPayload adds the payload to the update song o k response
func (o *UpdateSongOK) WithPayload(payload *models.Error) *UpdateSongOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update song o k response
func (o *UpdateSongOK) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSongOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSongBadRequestCode is the HTTP code returned for type UpdateSongBadRequest
const UpdateSongBadRequestCode int = 400

/*
UpdateSongBadRequest Bad request

swagger:response updateSongBadRequest
*/
type UpdateSongBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateSongBadRequest creates UpdateSongBadRequest with default headers values
func NewUpdateSongBadRequest() *UpdateSongBadRequest {

	return &UpdateSongBadRequest{}
}

// WithPayload adds the payload to the update song bad request response
func (o *UpdateSongBadRequest) WithPayload(payload *models.Error) *UpdateSongBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update song bad request response
func (o *UpdateSongBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSongBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSongInternalServerErrorCode is the HTTP code returned for type UpdateSongInternalServerError
const UpdateSongInternalServerErrorCode int = 500

/*
UpdateSongInternalServerError Internal server error

swagger:response updateSongInternalServerError
*/
type UpdateSongInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateSongInternalServerError creates UpdateSongInternalServerError with default headers values
func NewUpdateSongInternalServerError() *UpdateSongInternalServerError {

	return &UpdateSongInternalServerError{}
}

// WithPayload adds the payload to the update song internal server error response
func (o *UpdateSongInternalServerError) WithPayload(payload *models.Error) *UpdateSongInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update song internal server error response
func (o *UpdateSongInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSongInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
