// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateSongHandlerFunc turns a function with the right signature into a update song handler
type UpdateSongHandlerFunc func(UpdateSongParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSongHandlerFunc) Handle(params UpdateSongParams) middleware.Responder {
	return fn(params)
}

// UpdateSongHandler interface for that can handle valid update song params
type UpdateSongHandler interface {
	Handle(UpdateSongParams) middleware.Responder
}

// NewUpdateSong creates a new http.Handler for the update song operation
func NewUpdateSong(ctx *middleware.Context, handler UpdateSongHandler) *UpdateSong {
	return &UpdateSong{Context: ctx, Handler: handler}
}

/*
	UpdateSong swagger:route PATCH /song/{id} Song updateSong

Update Song
*/
type UpdateSong struct {
	Context *middleware.Context
	Handler UpdateSongHandler
}

func (o *UpdateSong) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateSongParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
