// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SongVersesResponse song verses response
//
// swagger:model SongVersesResponse
type SongVersesResponse struct {

	// verses
	// Required: true
	Verses []*SongVerse `json:"verses"`
}

// Validate validates this song verses response
func (m *SongVersesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVerses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SongVersesResponse) validateVerses(formats strfmt.Registry) error {

	if err := validate.Required("verses", "body", m.Verses); err != nil {
		return err
	}

	for i := 0; i < len(m.Verses); i++ {
		if swag.IsZero(m.Verses[i]) { // not required
			continue
		}

		if m.Verses[i] != nil {
			if err := m.Verses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("verses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("verses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this song verses response based on the context it is used
func (m *SongVersesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateVerses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SongVersesResponse) contextValidateVerses(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Verses); i++ {

		if m.Verses[i] != nil {

			if swag.IsZero(m.Verses[i]) { // not required
				return nil
			}

			if err := m.Verses[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("verses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("verses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SongVersesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SongVersesResponse) UnmarshalBinary(b []byte) error {
	var res SongVersesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
