// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateSongBody update song body
//
// swagger:model UpdateSongBody
type UpdateSongBody struct {

	// group
	Group string `json:"group,omitempty"`

	// link
	Link string `json:"link,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// release date
	ReleaseDate string `json:"release_date,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this update song body
func (m *UpdateSongBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update song body based on context it is used
func (m *UpdateSongBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateSongBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateSongBody) UnmarshalBinary(b []byte) error {
	var res UpdateSongBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
